PROGRAM IO_File_Write

    !********************************************
    !   WRITE DATA ON FILE
    !*******************************************
    
    ! Raise error if a variable not explicitely declared
    implicit none

    ! Variable declarations
    integer :: i, file_ID
    integer :: unit_number      ! for file creation
    integer :: num_digits
    double precision :: x
    character(len=50) :: filename
    character(len=10) :: formatted_number
    character(len=20) :: format_string
    character(len=20) :: filename_prefix
    character(len=4)  :: filename_suffix

    ! Build the filename. Example : output_0027.vtk 
    filename_prefix = 'output_'
    filename_suffix = '.vtk'
    num_digits      = 4             ! Number of digits    
    file_ID         = 27                
    write(format_string, '(A,I0,A,I0,A)') '(I', num_digits, '.', num_digits, ')'    ! Build format string
    write(formatted_number, trim(format_string)) file_ID                            ! Format file_ID
    filename = trim(adjustl(filename_prefix)) // trim(adjustl(formatted_number)) // filename_suffix               ! Concatenate strings

    ! Open the file
    unit_number = 10  ! Arbitrary unit number for the file
    open(unit=unit_number, file=filename, status='replace')

    ! Write preamble of the file
    write(unit_number, '(A)') "# vtk DataFile Version 5.1"
    write(unit_number, '(A)') "Generated by SolverX"
    write(unit_number, '(A)') "ASCII"
    write(unit_number, '(A)') "DATASET POLYDATA"
    write(unit_number, '(A)') "POINTS 3 float"

    ! Write content of the file
    x = 14.2654784134d0
    i = 1
    write(unit_number, '(I3, E20.10, E20.10, E20.10, E20.10)') i, x, x+i, x+2*i, x+3*i
    i = 4
    write(unit_number, '(I3, E20.10, E20.10, E20.10, E20.10)') i, x, x+i, x+2*i, x+3*i
    i = 3
    write(unit_number, '(I3, E20.10, E20.10, E20.10, E20.10)') i, x, x+i, x+2*i, x+3*i

    ! Close file
    close(unit_number)

END PROGRAM IO_File_Write
